version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            .venv/bin/activate
            pytest test_calculator.py
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
